language: ruby
cache: bundler
rvm:
  - 2.2.3
sudo: false

# we need a more recent cmake than travis/linux provides (at least 2.8.9):
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

